### ISSUE TITLE
Compatibility with Product Bundles extension

### ISSUE THREAD

**Issue by cturnbull** [krokedil/klarna-checkout-for-woocommerce#111]
KCO introduces quantity selection fields to the order review:

https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/ce8cbec7a7909b57b877d348a9a23ab0c73f43fa/klarna-checkout-for-woocommerce.php#L151

With bundle products where the quantity is fixed for the child products, it's normally only possible to alter the quantity on the bundle product itself. The filter above, however, adds a quantity field to every product, regardless of whether it's a bundle product child or not, to the order review in the checkout.

I have removed this filter for now, but it's a nice feature to be able to change quantities in the order review. Therefore would like to request a compatibility fix for Product Bundles. Thanks

**Comment by NiklasHogefjord** [comment]
Hi @cturnbull,
Sorry for the veeery late reply.

We will look into this. Our intention is to move this functionality into a separate plugin instead of having it in the KCO plugin. Some stores does not want the quantity field to be editable at all. 

If we move it to a separate plugin we can add more features to it as well.

**Comment by NiklasHogefjord** [comment]
We have added a s etting to turn this feature on/off in version 2.0.0.
