### ISSUE TITLE
Add to payment method title for emails and order review to show the payment method used in Klarna.

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/klarna-checkout-for-woocommerce#121]

**Comment by kristibarbosky** [comment]
Requested Klarna to provide localized names for order GET at https://jira.int.klarna.net/jira/browse/JT-1635

**Comment by kristibarbosky** [comment]
Klarna does not currently support localized names for the customer's chosen payment method category, so closing this ticket since this is not a Woo issue then.  In order to support this enhancement, Klarna would have to provide the data for the Woo plugin to provide it.  If merchants would like this functionality, they will need to contact Klarna directly.
