### ISSUE TITLE
Expired session when emptying a cart on checkout page

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/klarna-checkout-for-woocommerce#169]
When emptying a cart on the checkout page I can see `Sorry, your session has expired. Return to shop` message for a short moment just before being redirected to the cart page.

Can the customer be redirected directly to the cart page in this case?

_WP 4.9.8, WC 3.5.5, Klarna 1.8.4_

**Comment by MichaelBengtsson** [comment]
@rafal-sokolowski Do you mean on the checkout page itself with the Klarna iframe or do you see this on the confirmation page? If this is on the checkout page itself then this is something that is controlled by WooCommerce and not us directly.

**Comment by NiklasHogefjord** [comment]
This is probably a problem related to a conflict with some kind of minification/optimization/cache plugin.

I'm closing this issue for now since this probably is more of a support question rather than a general issue with the KCO plugin. Please get in touch with us at support@krokedil.com if you need help with troubleshooting.
