### ISSUE TITLE
KCO not showing up on manually created orders

### ISSUE THREAD

**Issue by dnkmdg** [krokedil/klarna-checkout-for-woocommerce#182]
Wordpress 5.1.0
WooCommerce 3.5.6
Klarna Checkout 1.8.4
Klarna Order Management 1.2.4

I've integrated the KCO with good result for regular checkouts, but for orders created from backend where users are instructed to pay order via mail, the KCO doesn't show up. See attachments.

<img width="432" alt="screen1" src="https://user-images.githubusercontent.com/6313551/54384757-4ef10300-4695-11e9-9b0d-f7cef6288760.png">
<img width="1191" alt="screen2" src="https://user-images.githubusercontent.com/6313551/54384756-4ef10300-4695-11e9-9d1d-8a8f1914928f.png">

<img width="1183" alt="screen3" src="https://user-images.githubusercontent.com/6313551/54384755-4ef10300-4695-11e9-8eba-8cabce390b29.png">

**Comment by MichaelBengtsson** [comment]
@foag 

Sadly this is not a supported feature in our plugin at the moment as we require a cart for the checkout process to work properly. This is however something that we have discussed supporting before, but it is not very high on our list of priorities for the plugin, since there are other features with a higher request rate. But as i have said, this is something that we have discussed, i just dont have any date for you for when it will be done.

**Comment by martinowren** [comment]
Do we have any updates on this feature?

**Comment by kristibarbosky** [comment]
@martinowren  - FYI - Woo Pay Link / draft orders integration/support has now been released for related Woo KP plugin, per https://github.com/krokedil/klarna-payments-for-woocommerce/issues/128.  Integration for this is also planned for Woo KCO, but no ETA available yet.

**Comment by muntjaber** [comment]
I am closing this since support for pay for order was [added in version 2.6.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/2.6.0).
