### ISSUE TITLE
Shippingng/invoice address format of KCO inconsistent with other checkout options: format issues and country missing

### ISSUE THREAD

**Issue by mnmedia** [krokedil/klarna-checkout-for-woocommerce#188]
Background: Shop based in Germany
Issue: recently I got a first order from Switzerland through KCO. It turned out, that KCO does not pass on the country to Woocommerce! 

Since in my shop settings the shipping documents are automatically processed and forwarded to my fulfilment company, the shipping returned, since the country was missing and also the person packaging did not realize it is an address abroad.

I realized then, that only KCO passes the addresses in an inconsistent format, which is different from what my woocommerce gets from orders on invoice or Paypal checkout. Those follow the standard German postal address conventions, while KCO seems to follow an US based convention (which is the way, also the Klarna order app website shows addresses). This would not be an issue, if the Country would be passed down to Woocommerce correctly!

So here is an example of the Standard Klarna address format and how it passes down:

John Doe
Main Street 123
Anytown
12345
AT        <- This is missing in Woocommerce after KCO orders

This is how it looks like in my German Woocommerce setting when using Paypal or invoice on checkout outside KCO:

John Doe
Main Street 123
12345 Anytown
Österreich         <- German spelling of Austria, Country is ALWAYS correctly passed down on invoice or Paypal orders

A solution is urgently needed, to pass down the country correctly. Preferably a solution through a code snippet. I still have to use KCO 1.8.0, since the issues with Germanized Pro and KCO 1.8.4 (  referenced elsewhere) are still not resolved, despite the topic has been closed:
https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/73

Best
Michael

**Comment by NiklasHogefjord** [comment]
Hi Michael,

During the process when the order is created in WooCommerce, the billing and shipping country is received from Klarna and saved in WooCommerce. You can see this in the plugin code here: https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/1.8.4/includes/class-klarna-checkout-for-woocommerce-confirmation.php#L218-L266.

If this isn't working in your store, this is more likely an isolated support question. Get in touch with us at support@krokedil.com and we will try to help you.

Regarding #73 I have re-opend the issue since we have had som issues with our extra checkout field logic and we are working on an improved logic for this.

**Comment by mnmedia** [comment]
FYI: The above issue was found to be present only in KCO versions higher than 1.7.9 ... In 1.7.9. The address data is communicated to Woo correctly. An involvement of other plugins was ruled out by subsequent deactivation and testing on my stagging site  ...
