### ISSUE TITLE
Snippet not getting updated with Total price when discount coupon used Or cart is updated

### ISSUE THREAD

**Issue by ritesh910sinha** [krokedil/klarna-checkout-for-woocommerce#189]
1. Look the below image when i have not used the coupon code
![kco1](https://user-images.githubusercontent.com/8166925/55425404-08117180-55a0-11e9-94af-c705951ae38c.jpg)
2. when coupon code used 
![kco2](https://user-images.githubusercontent.com/8166925/55425433-18295100-55a0-11e9-9854-0a108d165265.jpg)
Look into the 2nd image the total in left and total in klarna snippet 

3. also if i go back to website and add more product , total in snippet does not get updated 
![image](https://user-images.githubusercontent.com/8166925/55425526-4dce3a00-55a0-11e9-9660-e87dc3a058f8.png)

**Comment by NiklasHogefjord** [comment]
Hi,

This happens because the needed _klarna-checkout-for-woocommerce.js_ isn't loaded on the checkout page.

Since this isn't a general issue with the plugin I'm closing this ticket. 

My suggestion is that you deactivate other plugins and switch theme to try to troubleshooting this error. If you can't solve it on your own, you're welcome to get in touch with us for support at support@krokedil.com.
