### ISSUE TITLE
Shipping methods in iframe error message

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#195]
Hi. I've set up a new test site to test the new shipping methods in iframe in KCO version 1.9.0

It seemed to work fine when there is only one shipping option, but if I try to select a different option I get this message:
![image](https://user-images.githubusercontent.com/799281/55627783-4f218180-57af-11e9-9944-db836c926e3e.png)

Steps to reproduce:
1. Set up a new WooCommerce shop
2. Set up a shipping zone (Norway) with 2 flat rates
3. Create a product, add it to cart and go to checkout
4. Fill in test details
5. Select Flat rate no.2

**Comment by NiklasHogefjord** [comment]
Hi @forsvunnet,
We haver tested and tried to replicate the issue on two different WP installations now but are not able to trigger the problem.

When the customer changes shipping method in the iframe a server callback is sent to the store. If the store doesn't reply with a json body and a 200 response then Klarna won't proceed with the purchase. Perhaps this is a situation where the callback gets blocked by the webserver or a plugin.

To investigate this further we would need a Klarna order id for the session or a correlation id (from the log). Perhaps it's better that you get in direct touch with us at support@krokedil.com and we can have a closer look at your site?

**Comment by forsvunnet** [comment]
We're using local development sites. The url's are not publically accessible. I'll test again on a test site that is accessible.

**Comment by MichaelBengtsson** [comment]
@forsvunnet We are closing this issue for now. If you are still getting problems with this, please reopen this issue again.

**Comment by Swagnus** [comment]
@forsvunnet did you solve this problem? I have the exact same problem and can't figure out why.

**Comment by NiklasHogefjord** [comment]
@Swagnus You need to enable this feature in an environment that is publicly available. Not a local environment. This is needed because Klarna sends a callback each time the shipping method is changed in the iframe and the store needs to respond to that callback.

Also - server firewalls and security plugins like Wordfence might block these callback.

**Comment by marcodisarno** [comment]
Hey there, facing the same problem when using KCO without multiple shipping options, simply by adding an `order_line` of type `shipping_fee` to the order.

I have a local environment as well, but I wouldn't know why Klarna has to know anything about my shipping in this case - I simply want it to pay the amount that is correctly displayed.

What am I not seeing here?

**Comment by MichaelBengtsson** [comment]
@marcodisarno As Niklas mentioned in his previous reply, this is because Klarna sends a callback to your server. Your server then needs to respond correctly to this to make this work properly.

The reason for this is to make sure that the Klarna order and the information in the store is synced up. Sadly there is nothing we can do about this since this is something required by Klarna.
