### ISSUE TITLE
Additional shipping method information should not be removed or modified

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/klarna-checkout-for-woocommerce#235]
When using a Bring service, I can add to a default shipping method a few helpful pieces of information like opening hours, distance, link to the location on the map etc.

I tried the following actions:
`woocommerce_cart_shipping_method_full_label`
`woocommerce_after_shipping_rate`

When I select a direct bank transfer or cash on delivery as my payment method, they work like a charm but Klarna has its own checkout page where the HTML code from additional information is stripped out.

klarna-checkout-for-woocommerce/assets/js/klarna-checkout-for-woocommerce.js

```
var shippingPrice = $("label[for='"+idVal+"']").text();
$(".woocommerce-shipping-totals td").html(shippingPrice);
```

I think this is not how it's supposed to work.

**Comment by NiklasHogefjord** [comment]
Hi,
Sorry for the late reply @rafal-sokolowski.

We use the WooCommerce function `woocommerce_order_review()` to display cart contents and shipping. That function calls the WooCommerce template checkout/review-order.php.

The JS example you refer to in `klarna-checkout-for-woocommerce.js` is only used when the KCO plugin setting i set to display shipping method in the Klarna Checkout iframe. Then **no** shipping selector should be displayed in WooCommerce, since selection of shipping method is done within the iframe.
