### ISSUE TITLE
Issue with thank you page in Woocommerce after Klarna Checkout order finished

### ISSUE THREAD

**Issue by drsounds** [krokedil/klarna-checkout-for-woocommerce#236]
It seems that Klarna Checkout doesn't use the standard thank you page route in Woocommerce but redirect to same checkout page with ?success=true instead, so thank you functionality provided by woocommerce or plugins doesn't work but instead get an empty page.

**Comment by NiklasHogefjord** [comment]
Hi @drsounds, thanks for the report.

We actually use the WooCommerce standard thank you functionality in the plugin but the one extra step is added to the checkout process because of how Klarna Checkout is designed.

* When the customer clicks the _Place order_ button in the KCO iframe, the customer is redirected to the _confirmation URI_ witch is the same as the checkout page with the added query parameter _?success=true_.
* When the _confirmation URI_ page has been rendered the standard WooCommerce checkout form is being submitted.
* The customer is finally redirected to the standard WooCommerce thank you page (e.g the order received endpoint). This part is entirely handled by WooCommerce.

For more information about the KCO checkout flow see https://docs.krokedil.com/article/144-klarna-checkout-integration-flow-chart.
