### ISSUE TITLE
Compatibility issue with Order Delivery Date for Woocommerce

### ISSUE THREAD

**Issue by jgangso** [krokedil/klarna-checkout-for-woocommerce#267]
Hi,

[It says in the Woocommerce Docs](https://docs.woocommerce.com/document/klarna-checkout-extra-checkout-fields/#section-5), that the plugin works with Order Delivery Date for Woocommerce -plugin.

It is true to the extent, that the chosen delivery date is being saved correctly to the order. However, the validation doesn't work as I would expect; If the date is set to be required, the checkout still gets submitted in the frontend, and naturally goes through at Klarna side. When returning to webshop, the order gets created via fallback mechanism since the validation at [`\Orddd_Lite_Process::orddd_lite_validate_date_wpefield`](https://www.tychesoftwares.com/docs/orddl-apidocs/source-class-orddd_lite_process.html#322-350) fails upon the Woocommerce checkout form submission.

Before making any workarounds, I'd like to know is this expected behavior, and is there eventually coming any fix from your side to this issue?

Thank you.

**Comment by MichaelBengtsson** [comment]
Hi @jgangso 

We are currently working on a bigger rewrite of the plugin that will make Klarna Checkout much more compatible with plugins such as these. This version should be ready for testing internally this week and we will then start testing it with merchants. Sadly i don't believe we will be able to resolve this issue before we get the rewrite out. So for now i would say that you would have to wait unless you want to make your own workaround. This is not expected behavior though.

Hopefully that helps!

**Comment by jgangso** [comment]
Thanks, that's enough information for now. Good luck releasing the rewrite of the plugin!
