### ISSUE TITLE
MC4WP newsletter checkbox

### ISSUE THREAD

**Issue by andresendo** [krokedil/klarna-checkout-for-woocommerce#293]
Hi,
we are using MC4WP: Mailchimp for WordPress - this plugin creates a additional checkbox  "subscribe to our newsletter" ... how can i show this checkbox while the klarna checkout!?

<img width="635" alt="Bildschirmfoto 2020-03-16 um 21 50 34" src="https://user-images.githubusercontent.com/255217/76798736-6f83f980-67d0-11ea-959e-51f72a62c17d.png">
Thanks and warm regards
andre

**Comment by MichaelBengtsson** [comment]
@andresendo 
We are compatible with Mailchimps own plugin for WooCommerce that you can find here:
https://wordpress.org/plugins/mailchimp-for-woocommerce/

This should work and do the same thing that you are trying to do.

For the future, if you have support questions like this, please mail our support at support@krokedil.com since this does not need to be an issue. I will be closing this since its not an actual issue.
