### ISSUE TITLE
Zero decimal support (previously: Checkout not working for Version 2.0.12 and WP 5.4 401 authorization required)

### ISSUE THREAD

**Issue by fracii** [krokedil/klarna-checkout-for-woocommerce#307]
I have updated from 2.0.11 and also updated Wordpress to 5.4. Customers got problem with the shipping frame disappearing both in Chrome and FF.

Now I when looking in to this I get this error when try to load Klarna Checkout as "customer":
**401 Authorization Required
openresty**

before I got above problem I also got problem that calculated "value is wrong" and maby perhaps this have to be with shipping problem.

API codes is as always been, and I have no testmode on.

We needed to disable Klarna.

Please fix this as soon as possbile.

Best Regards

Viktor

**Comment by fracii** [comment]
I had to change API credits and also put 2 decimals in WooCommece Settings to get it to work again. But now I have 2 decimals in all shop. Any fix for this?

**Comment by MichaelBengtsson** [comment]
Hi @fracii 
Zero decimals depends on what settings you are using for taxes and other things. Sadly this is a very hard thing to get correct because the setting that claims its only used for displaying prices in WooCommerce with decimals is also used to do the calculations from WooCommerce regarding the prices. We are working on it but we do not have a 100% secure fix at the moment sadly.

**Comment by kristibarbosky** [comment]
related to: https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/38

**Comment by MichaelBengtsson** [comment]
Hi @fracii

This issue should be resolved with the latest version, 2.2.0.

I will close this issue, but if it still remains an issue for you, then i will reopen it.
