### ISSUE TITLE
Possible issue between Klarna and Vipps?

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#376]
Some of our orders paid with Vipps change payment gatewate to Klarna when trying to fulfill/complete the order. This only happens to a fraction of all our Vipps-orders, so we're not able to replicate the issue, but it happens often enough that it is problematic. We've experienced it on two different sites, but they share a lot of the settings.

### Klarna plugin version
2.4.2.

### WordPress version
5.6

### WooCommerce version
4.8.0

### Screenshots
![Screenshot_2021-01-19 Rediger ordre ‹ Organized no — WordPress](https://user-images.githubusercontent.com/24268072/105043503-e8458900-5a65-11eb-8f13-8b3e5f02e0b3.png)

**Comment by MichaelBengtsson** [comment]
Hi @orjansteffensen.

I would recommend that you send a support ticket, since we might need to get access to your site to test this. However, i would also suggest that you contact Vipps, since they have directly integrated with our plugin to support the external payment methods part in their plugin. If this is what you are using as well, then i would suggest that you also contact them. Since the order here says that the payment method is Klarna, it seems like something caused it to switch. Our Klarna order management plugin would not cause this, since we have no code that would do this at all.

Without looking at this too much, i believe that the issue might be in the Vipps plugin to start with, but we can of course help investigate this in a normal support ticket. You can contact our support at support@krokedil.se

I will be closing this for now. And if needs be i will reopen it again if there is something that we need to change in our code.
