### ISSUE TITLE
Receiving error: required_fields in callback

### ISSUE THREAD

**Issue by jonasostrom** [krokedil/klarna-checkout-for-woocommerce#66]
I'm getting ?required_fields=WyJ0ZXJtcyJd  which is decoded to "terms".
Though I'm not running my klarna with terms-checkbox enabled.
Even if "Terms and conditions checkbox" is enabled AND I check the terms, I receive the same error in 
required_fields.

What am I doing wrong?
Running v3 1.5.2

**Comment by kristibarbosky** [comment]
@jonasostrom - Please double check under WooCommerce->Advanced to make sure the store has a Terms page chosen in the drop down, see example screen shot below.  This page is required for KCO.

![image](https://user-images.githubusercontent.com/15654455/41907533-2f1b2cb2-790f-11e8-9b7c-25ca0aa8179b.png)

**Comment by NiklasHogefjord** [comment]
This was a confirmed bug when switching between KCO and another payment method before trying to complete the purchase with KCO (or not having KCO as the default payment method).

The issue hould be fixed in version 1.5.5 here: https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.5.5
