### ISSUE TITLE
Enhancement to add shipping options within the KCOv3 iframe

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#68]
Per: https://developers.klarna.com/api/#checkout-api__create-a-new-order__shipping_options

**Comment by forsvunnet** [comment]
Any ETA on the implementation of this? It would make the workaround I built in our bring fraktguiden plugin redundant and provide a better customer experience.

**Comment by MichaelBengtsson** [comment]
@forsvunnet We don't currently have a ETA for this, however i will start looking at it during this week. But due to vacations we don't have an exact date for when we will have it finished.

**Comment by TheWizl** [comment]
![kco kassa - woocommerce - frakt](https://user-images.githubusercontent.com/67698/45021673-76a24700-b032-11e8-9455-d29b0c1899ef.png)

Är det detta som det inte finns stöd för nu?

**Comment by forsvunnet** [comment]
@MichaelBengtsson any progress on this?

**Comment by NiklasHogefjord** [comment]
@forsvunnet,

I've started looking into this. 

At the moment we're finishing up the transients/session storing of extra fields & 0 decimals. We aim to release that during this week. 

I will then get into the development of shipping options inside KCO checkout. I hope to have something that can be tested during last week of January.

**Comment by NiklasHogefjord** [comment]
I have been working on this and now I got a first version that you can test.

* The plugin can be downloaded from the develop-shipping-display branch here: https://github.com/krokedil/klarna-checkout-for-woocommerce/tree/develop-shipping-display.
* An example of how it looks with Storefront as the active theme can be viewed here: https://demo.krokedil.se/klarnacheckout/

To activate this feature navigate to _-> WooCommerce --> Settings --> Payments --> Klarna Checkout_. Scroll down to the Shipping settings section and tick the box _Shipping methods in iframe_.
 
![image](https://user-images.githubusercontent.com/985946/53642781-cd2fbd00-3c32-11e9-8762-1721a9033251.png)

## Behaviour

When this feature is activated, shipping methods will be displayed inside the Klarna iframe, like this:

![image](https://user-images.githubusercontent.com/985946/53642993-462f1480-3c33-11e9-8b18-61b9fb511f49.png)

Instead of displaying all shipping methods in WooCommerce order review, only the price and shipping method name of the selected shipping method will be displayed like this:

![image](https://user-images.githubusercontent.com/985946/53643401-3d8b0e00-3c34-11e9-8db2-f9b7bbbfe2e5.png)

## Compatibility with WooCommerce and other plugins 
When the customer clicks the _Place order_ button the checkout page is reloaded and a confirmation process begins. In this process the regular WooCommerce checkout form is populated with address data and the checkout form is then submitted.

To be able to be compatible with this flow (and possibly with other plugins during the entire checkout process) we keep the regular shipping option radio buttons present inside the WooCommerce checkout form. To hide them from the customer (since selection of shipping methods now is handled by the customer inside Klarnas iframe) we hide them with the following CSS:

```
.kco-shipping-display ul#shipping_method {
    position: absolute;
    top: -9999px;
    left: -9999px;
}
```

We will do more testing around this next week. Any suggestions, bug reports and questions are very welcome :).

**Comment by yratof** [comment]
Is this tested and ready for production? I have an email from Klarna directly saying that this needs to be implemented before we can take a shop live

**Comment by MichaelBengtsson** [comment]
@yratof This has been tested by us internaly and by our contact at Klarna and we belive it is ready for production. However we have not released an update with this yet. You can test the feature if you download this branch: https://github.com/krokedil/klarna-checkout-for-woocommerce/tree/develop-shipping-display

This will however be released soon in the full version of the plugin.

**Comment by MichaelBengtsson** [comment]
That branch is based on the 1.8.4 release, so it should be up to date with the current master branch and the latest released version of the plugin. If possible i would recomend that you test it first howerver in a staging site or making sure that you can roll back if you discover any issues.

You can also see what it looks like in our demo store at https://demo.krokedil.se/klarnacheckout/

**Comment by NiklasHogefjord** [comment]
@yratof Why does Klarna say that this needs to be implemented before you can take the shop live?

**Comment by oliverbajusz** [comment]
There was a miscommunication. Since this ticket was open for so long I thought it was already released. @yratof as we talked about this today this is not a must have requirement.

**Comment by NiklasHogefjord** [comment]
Thanks for the answer @oliverbajusz.

@yratof there's a PR for this feature in Develop branch now - https://github.com/krokedil/klarna-checkout-for-woocommerce/pull/183. We will merge it later today. Scheduled release Tuesday or Wednesday this week.

**Comment by NiklasHogefjord** [comment]
It took more time than expected but [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0) is now live.
