### ISSUE TITLE
Add support for WooCommerce Germanized plugin [PI-587]

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#73]
https://github.com/vendidero/woocommerce-germanized

**Comment by kristibarbosky** [comment]
Today I've received an internal Klarna email about this issue too:here is a german merchant (OnoLabs) trying to get live with KCOv3 but they've debugged to find:
In short: there seem to be a module called Germanized which creates the problem, that I can't place orders with KCO any more.
I always get this error when I hit the "buy" button, but as far as I know it's not our fields, which is missing there:
https://www.screencast.com/t/HGCdBYNbZ

Per Slack chat, Niklas will review this ticket further later this week to determine scope of effort and best next steps.

**Comment by kristibarbosky** [comment]
A merchant has been able to proceed with KCO with the Germanized plugin.  A few points to note:

1. DHL is not yet supported by Klarna for KCOv3.
2. The Germanized plugin has many settings that could be incompatible with KCO (such as required fields during checkout).  Merchants will have to carefully configure and test both plugins to ensure compatibility, but it seems German checkout requirements can sufficiently be handled within KCO.

**Comment by NiklasHogefjord** [comment]
Hi @mnmedia,
Do you use this Germanized plugin: https://github.com/vendidero/woocommerce-germanized?

If it is a matter of improving the check to see if _Germanized terms and conditions_ and _GDPR & cancelation policy_ is checked we can probably fix this.

**Comment by mnmedia** [comment]
Yes, @NiklasHogefjord,

it is the Germanized Plugin by Vendidero.

And yes, I am sure that it will be solved, if the  _Germanized terms and conditions and GDPR & cancelation policy_ check box can be part of the Klarna checkout, because the system clearly states that the fallback is created due to the missing check by the customer. I asume the missing "new order" email to the administrator is then a consequence of the fallback.

In the Klarna System, the order is present, so transmission of data is not affected.

Thanks for your effort. Looking forward to a solution. Even a temporary fix by having some php code additions until the next update would be fine.

**Comment by annikagievers** [comment]
Hey there

I had to solve the same problem for my client.
Since Klarna only links to their own terms and conditions and the Germanized checkboxes are not compatible with Klarna Checkout, I found following solution:

I deactivated the Germanized checkout checkboxes in the backend (you can find this option under „Rechtliche Checkboxen“).
Then I added the needed links under the order notes (simply add it to your functions.php):
```
add_action( 'woocommerce_after_order_notes', 'privacy_terms' );

function privacy_terms() {
 echo 'needed texts and links';
    }
```

I hope this helps!

**Comment by mnmedia** [comment]
@NiklasHogefjord @kristibarbosky 
Any development on this issue?
What if you implement to grab the Germanized plugin terms and conditions checkbox (if Germanized is in place) and replace the checkbox which refers to the "AGB" (selling conditions of the vendor) that Klarna checkout uses. By any means, the Germaized terms and conditions checkbox is more complete, since it refers to all three necessary pages: selling conditions, cancellation policy and data protection policy.

**Comment by NiklasHogefjord** [comment]
Hi @mnmedia,
This will take more time and effort to solve than what I originally thought. We need to go through this more in detail to see in what way we can solve this. I'm afraid I don't have an ETA for when this can be solved.

**Comment by mnmedia** [comment]
Hi @NiklasHogefjord 
if you need information on the exact checkbox, I can provide input. What I found interesting is that you already have this functionality for the standard Woocommerce terms & conditions checkbox:
![grafik](https://user-images.githubusercontent.com/45258802/49743435-fd526a00-fc9a-11e8-87e4-925d57330458.png)
This basically doubles the checkbox for terms, since Klarna Checkout asks for checking the shops terms anyway. Wouldn't it be possible to implement the same choice for the Germanized checkbox. Attached, please find the terms.php from the Germanized plugin that controls this checkbox (child-theme/woocommerce-germanized/checkout/terms.php)
[terms.php.txt](https://github.com/krokedil/klarna-checkout-for-woocommerce/files/2663797/terms.php.txt)
If I can provide more info, I happy to support with whatever I can find.
Thank you

**Comment by MichaelBengtsson** [comment]
@mnmedia and @annikagievers 

We are working on this issue at the moment and we have a way to solve this now. But we need to resolve some other things that surround the fix for this issue.

The fix itself will involve the ability to add the checkbox from the Germanized plugin to the checkout through an action. And then we will validate this before a Klarna order is completed, to ensure that no order is created unless it should be. We will provide a code example of how to do this, but it wont be included directly in the plugin.

**Comment by mnmedia** [comment]
Hi @MichaelBengtsson,

that sounds good. I'm looking forward. Vendidero, the developer of Germanized is aware of this thread and stated to me that they are willing to take care from their side that compatibility will remain throughout future development of Germanized once a solution is found.

Thank you
Michael

**Comment by visualmovement** [comment]
Hi @MichaelBengtsson 
any Update on this issue? This is eventually what stops us from switching to klarna checkout atm. 

Thank you
Sven

**Comment by stecrz** [comment]
Hello! The most recent update (1.8.0) seems to fix some issues. E. g. the "legal" checkbox is visible now! Also, I now receive the order email automatically (both vendor and customer).

But: The customer receives the order confirmation email **three** times and the payment method is shown as "PayPal" instead of "Klarna" in the confirmation email. After the payment ist being finished, the customer is not **redirected to the store**s success page. Instead, the PayPal checkout opens, so that the customer might pay twice... 

PayPal is my default (first) payment option - could this be the reason for that? Maybe it was tested with Klarna being the first (default) and only payment option?

Thanks for the support!

**Comment by NiklasHogefjord** [comment]
When the next version is released @stecrz, you can use the following code to display the checkbox:
https://gist.github.com/krokedilgists/7fab7cf5d6a7b3c52fdd6bbc641592d0

**Comment by NiklasHogefjord** [comment]
@stecrz If the emails isn't sent I think that there might be something else that cause this issue. But we will take an extra look.

**Comment by stecrz** [comment]
I just recognized that the payment is not possible at all. I used the code you linked for adding the legal checkbox, but no matter if the user clicks the checkbox or not, he will receive the error message "The following fields are required: legal.".

**Comment by MichaelBengtsson** [comment]
Closed since this has been resolved. Update to use the latest version of the gist and the current version of KCO. You can find the gist here: https://gist.github.com/krokedilgists/7fab7cf5d6a7b3c52fdd6bbc641592d0

**Comment by mnmedia** [comment]
@MichaelBengtsson 

Since I had been extensively travelling between January and End of February, I only today updated to Version 1.8.4 from 1.8.0 which had been working for me before.

Like stecrz reported, I ran into the same issue: no payment/order possible! However, even after rolling back to 1.8.0 the problem perists now. The error message is:
![grafik](https://user-images.githubusercontent.com/45258802/54550136-bbc50f80-49ab-11e9-97eb-288e15f0e5b9.png)

No matter which checkboxes withing Germanized Pro or Klarna Checkout I activate or deactivate, it does not work.
![grafik](https://user-images.githubusercontent.com/45258802/54550355-224a2d80-49ac-11e9-8868-cd40f30a7e82.png)

This error message occurs now no matter whether or not I add the gist to my functions.php

So, since I switched completely to Klarna after it worked for a while with 1.8.0, basically the shop is now dysfunctional, unless I switch back to Paypal, which I would like to avoid, since in general i find the Klarna system more convincing, apart from the Klarna Checkout Plugin issues, though!

Thus an urgent solution is needed

**Comment by NiklasHogefjord** [comment]
We have had some issues with the extra checkout field logic. We are working on an improved solution for this. It will be released in version 1.9.0 that is scheduled to go live today or tomorrow.

**Comment by mnmedia** [comment]
@NiklasHogefjord 
Just to let you know, I played around with the settings. Once I rolled back to 1.8.0 the error message changed from:
"The following fields are required: gzdp_privacy_policy legal." to
"The following fields are required: gzdp_privacy_policy." 
Then I realized the error is only present, when I try to order as a logged in user. It does not appear for guest orders (which are the meajority of orders in my shop) ...

**Comment by flymke** [comment]
I stumbled across this thread and had the same issue.

What I did was that I enabled the checkbox in the Klarna Checkbox Plugin and disabled the checkbox from Germanized via PHP. You can do that by overriding the template located under woocommerce-germanized/checkout/terms.php:

`
// ...
if(WC()->session->get('chosen_payment_method') == 'kco') {
	add_filter( 'woocommerce_germanized_checkout_show_terms', '__return_false' );
}
if ( apply_filters( 'woocommerce_germanized_checkout_show_terms', true ) ) : ?>
// ...
`
Might not be the best solution, but it works.
