### ISSUE TITLE
Incorrect use of transients

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#93]
While working on a new project I came across this code that caused a fatal error.

https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/7ab92e827d0e9f2171c7208b153596fda5acbc2a/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L192

The surrounding code looks like test-code so I thought I should make an issue in case this is something that slipped through reviews.

**Comment by MichaelBengtsson** [comment]
@forsvunnet Yes there are some things that needs to be redone arround this part of the code, and it seems we missed one test row there. 

However, the transient works in our testing and for other merchants. So could you provide me with the fatal error that you are getting?

**Comment by MichaelBengtsson** [comment]
Closed due to no reply.

**Comment by MichaelBengtsson** [comment]
@forsvunnet Yes the naming of the transient is bad, and we have plans to update that to solve any potential issues by adding a prefix to the ID. 

The reasson why we decided to use a transient in this case is that it is more reliable then sessions, which we have had issues with in the past. Where for some sites the sessions don't get set properly or at all, and since this is used before we have an order we decided to use a transient. But we will take what you say under advisement and see if we need to change this.

**Comment by forsvunnet** [comment]
I would recommend using order meta to store this information then. Transients are meant to be used as a cache. There is much discussion about when and how transients should be used, but I won't get into details on that here.

From the documentation on transients:

> Furthermore, it is possible for the transient to not be available before the expiration time. Much like what is done with caching, your code **should have a fall back method to re-generate the data** should the transient not be available.

**Comment by NiklasHogefjord** [comment]
For the record, the naming of the transient has been fixed now in 05c3d17fbb583742502e8007317e587c63fe74c3.

As for using order meta this is not possible with this plugin. The order in WooCommerce is created _after_ the purchase is finalized in Klarnas system. So when the customer clicks the _Place order_ button and the validate callback happens, there is no order in WooCommerce (more detailed info about the KCO checkout flow can be found here: https://docs.woocommerce.com/document/klarna-checkout-integration-flow-chart/). 

Since this is a server-to-server callback we are not able to use session storage for storing the data needed in the validate callback. 

As you say @forsvunnet, as described in the WP Transients API documentation it is not the optimal way to store this data since it _might_ be erased before the expiration time. The two ways I see this being solved is to either move them to a custom post type or into a custom table.

Any thoughts on that?

**Comment by forsvunnet** [comment]
That sounds like a good solution. Alternatively, you could do it the WordPress way of just creating an order and give it status `wc-auto-draft`.

I can also confirm that use of transients is causing problems when using external caching. We use Redis object-caching on all our sites and we're seeing orders that are coming in with missing meta-data. The missing meta is things like color/size selection (variation) and order number (note: not the same as ID).
We'd appreciate it if this issue is prioritised as this is urgent for our client.

**Comment by NiklasHogefjord** [comment]
Thanks for the feedback @forsvunnet. We will prioritise this issue.

I want to avoid creating an order before the purchase is completed so I guess we'll look into a CPT or a custom table.

When it comes to missing meta data in orders, that is probably more session related. It has nothing to do with data stored in transients. The transient is currently used for two things:

1. Storing information about extra form fields (other than the default checkout fields) to that we can make sure all required fields have been populated before approving a purchase in Klarna.

1. Storing a cart hash that is used for comparison so that the order in Woo matches the order in Klarna (before approving the purchase in Klarna).

Perhaps we can have a closer dialogue about the order meta issue when rewriting this feature as well? Perhaps a good idea to do that via email.

**Comment by MichaelBengtsson** [comment]
@forsvunnet Just a quick update.

We are working on this at the moment and i hope to have a development version ready for testing this week. 

We found a way to access the session information from the database so that we can use that even for the server to server calls. This is however a big change that needs a bit of testing, which is why its taken some time to do.

**Comment by NiklasHogefjord** [comment]
Hi @forsvunnet,
The new feature of handling extra checkout fields is now live in version 1.8.1 (https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.8.1).

* Storing of data in transients is now removed completely in the plugin.
* Information about extra checkout fields is now stored in session data.
* The session ID is added to Klarna so we can use session/cart in validate & push notifications from Klarna (server to server callbacks). 

You can see how we handle session in callbacks here https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L234 and here https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L46-L47.

We will go through and improve this. The validation_cb() function absolutely needs some attention and improvement.

I'm closing this issue now. Please feel free to re open it again you you have any questions/concerns.

**Comment by forsvunnet** [comment]
Hi. I got an email from a customer that's having trouble with the new implementation. Could it be the rounding that's being applied by intval here? 
https://github.com/krokedil/klarna-checkout-for-woocommerce/blame/7c2eea1a45ca8d454edbbfc8f7f53e91b5c53b8b/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L353

This is the error message he's getting:
![image](https://user-images.githubusercontent.com/799281/51968578-953a2c00-2472-11e9-9c85-6b7d781f9663.png)

**Comment by NiklasHogefjord** [comment]
@forsvunnet I will look into it. Do you know what the customer had in his cart?

**Comment by lecklin** [comment]
@NiklasHogefjord we also received a message from a customer last weekend that they got the same error message that @forsvunnet posted above.

The cart in question had multiple items.

Purchases with multiple items have been made without an issue before and after this, so the issues seems somewhat random.
Everything on the site was running on the latest versions at the time of the error.

**Comment by MichaelBengtsson** [comment]
This should be fixed now. If this is not the case then please reopen the issue.
